# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformDocs < Formula
  desc "Generate documentation from Terraform modules in various output formats"
  homepage "https://github.com/terraform-docs/"
  version "0.18.0"

  on_macos do
    on_intel do
      url "https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-darwin-amd64.tar.gz"
      sha256 "2b4717e979941bfaf9225c66463fe8962c33713d5f15c2aa764c55d7d6a0b689"

      def install
        bin.install "terraform-docs"
      end
    end
    on_arm do
      url "https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-darwin-arm64.tar.gz"
      sha256 "90654f8436ee28f9a245d9b6af88ba305b09c6cd773588b9362c29f76dad1732"

      def install
        bin.install "terraform-docs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-linux-amd64.tar.gz"
        sha256 "7ccf78ca447e155ebf8ff0a390826283eded651d55b8e68cc534998f8f5fac2c"

        def install
          bin.install "terraform-docs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-linux-arm.tar.gz"
        sha256 "2d081a236be6fcd8f960434404054666859f0737ee29ed3ceed8aab68064f1c1"

        def install
          bin.install "terraform-docs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-linux-arm64.tar.gz"
        sha256 "c131bbe493cd97ee67a9b523264cc6bb4bb25aa506d65249cfb5913c5f64e772"

        def install
          bin.install "terraform-docs"
        end
      end
    end
  end

  test do
    system "#{bin}/terraform-docs version"
  end
end
