# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformDocs < Formula
  desc "Generate documentation from Terraform modules in various output formats"
  homepage "https://github.com/terraform-docs/"
  version "0.11.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/terraform-docs/terraform-docs/releases/download/v0.11.2/terraform-docs-v0.11.2-darwin-amd64.tar.gz"
    sha256 "ac7ce685dea91212199c58de2379b419a5f512f70eda08b435176c1b5594716c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/terraform-docs/terraform-docs/releases/download/v0.11.2/terraform-docs-v0.11.2-linux-amd64.tar.gz"
    sha256 "daae08cc21d639bb88697d6caae7efc8eb17c44ff30aff7e801bd4d34ac8372c"
  end

  def install
    bin.install "terraform-docs"
  end

  test do
    system "#{bin}/terraform-docs version"
  end
end
